services:
  - type: web
    name: interview-collab-backend
    env: node
    buildCommand: cd backend && npm install --no-optional
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false